### ISSUE TITLE
Instructions for ESP32 Arduino and PlatformIO

### ISSUE THREAD

**Issue by marcelstoer** [nopnop2002/esp-idf-net-logging#2]
This library looks fantastic, thank you!

Are there instructions somewhere how (if at all) I could integrate this into an Arduino core ESP32 project built with PlatformIO?

**Comment by nopnop2002** [comment]
this might help.

However, I have never used Arduino Core for ESP32.

https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/esp-idf_component.html

---

Arduino Core for ESP32 does not support all functions of ESP-IDF

Some functions may not be available on Arduino Core for ESP32.

**Comment by marcelstoer** [comment]
> this might help

😄 I know that chapter but it describes the other way around - Arduino as an IDF component. 

> Arduino Core for ESP32 does not support all functions of ESP-IDF

True, so far it's been sufficient for all my projects.

**Comment by nopnop2002** [comment]
This is the code for a very basic mqtt publish.

How about trying to see if this can be built in the Arduino environment first?

https://github.com/nopnop2002/esp-idf-net-logging/blob/main/components/net-logging/mqtt_pub.c


You may be able to compile if you change from .c to .cpp.
