### ISSUE TITLE
IRAM usage

### ISSUE THREAD

**Issue by phatpaul** [nopnop2002/esp-idf-net-logging#4]
Adding this as a component to my project pushed me over the limit of IRAM on the ESP32.  Before including this component, my `idf size`:
```
Used static DRAM:   61924 bytes (  62656 remain, 49.7% used)
      .data size:   24236 bytes
      .bss  size:   37688 bytes
Used static IRAM:  129754 bytes (   1318 remain, 99.0% used)
      .text size:  128727 bytes
   .vectors size:    1027 bytes
Used Flash size : 1577277 bytes
      .text     : 1082459 bytes
      .rodata   :  494562 bytes
Total image size: 1731267 bytes (.bin may be padded larger)
```
And when it is enabled (by a call in main.c:  udp_logging_init("255.255.255.255", 6789, true);
```
Used static DRAM:   61924 bytes (  62656 remain, 49.7% used)
      .data size:   24236 bytes
      .bss  size:   37688 bytes
Used static IRAM:  131502 bytes (   -430 remain, 100.3% used) Overflow detected! You can run idf.py size-files for more information.
      .text size:  130475 bytes
   .vectors size:    1027 bytes
Used Flash size : 1578629 bytes
      .text     : 1083683 bytes
      .rodata   :  494690 bytes
Total image size: 1734367 bytes (.bin may be padded larger)
```

That caused the linker to fail because I'm out of IRAM.  The difference in IRAM is 1748 Bytes.
Comparing the outputs from `idf size-files`, I see that there is a new entry stream_buffer.c.obj which is using 781 bytes of IRAM.  That doesn't seem to completely account for the increase, but it is significant.  
xMessageBufferCreate() is a macro that points to xStreamBufferGenericCreate() in stream_buffer.c.  

I know this is not a bug, but I wonder is it necessary to use this stream buffer method for this log redirect feature?  Or is there a more lightweight method that can work?  And does it need to use IRAM?

**Comment by nopnop2002** [comment]
This project uses a communication task in the background.

Background communication tasks perform UDP communication, TCP communication, MQTT communication, or HTTP communication.

xMessageBuffer is used to communicate with background communication tasks.

ESP-IDF provides several component  of inter-task communication.
- xMessageBuffer
- xStreamBuffer
- RingBuffer
- Queue

Whether or not to use IRAM is component dependent.
I don't know how IRAM is used inside the component.
Queue only supports fixed lengths, so it's not suitable for this project.


This is xMessageBuffer:
```
Used static DRAM:   10600 bytes ( 170136 remain, 5.9% used)
      .data size:    8432 bytes
      .bss  size:    2168 bytes
Used static IRAM:   50674 bytes (  80398 remain, 38.7% used)
      .text size:   49647 bytes
   .vectors size:    1027 bytes
Used Flash size :  132947 bytes
           .text:   93907 bytes
         .rodata:   38784 bytes
Total image size:  192053 bytes (.bin may be padded larger)
```

This is RingBuffer:
```
Used static DRAM:   10600 bytes ( 170136 remain, 5.9% used)
      .data size:    8432 bytes
      .bss  size:    2168 bytes
Used static IRAM:   51870 bytes (  79202 remain, 39.6% used)
      .text size:   50843 bytes
   .vectors size:    1027 bytes
Used Flash size :  133431 bytes
           .text:   93903 bytes
         .rodata:   39272 bytes
Total image size:  193733 bytes (.bin may be padded larger)
```
---

You will notice that your project is already using a large amount of IRAM before using this library.
Using IRAM_ATTR consumes IRAM.
```
Used static IRAM:  129754 bytes (   1318 remain, 99.0% used)
```

**Comment by phatpaul** [comment]
Thanks for your response.  
I was just looking at [ring buffers](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos_additions.html#ring-buffers).  Even though RingBuffer appears to use more IRAM, I think ESP-IDF already uses RingBuffer internally for some drivers, so using them may be preferred to xStreamBuffer/xMessageBuffer which were not already used.
Do you have an implementation which uses RingBuffer that I could try?

**Comment by nopnop2002** [comment]
Please temporarily add xRingbufferCreate() to your project and tell me the amount of IRAM.
```
xRingBuffer = xRingbufferCreate(1024, RINGBUF_TYPE_NOSPLIT);
```

**Comment by phatpaul** [comment]
Great idea to test the theory first.  I did this, and my program still fits in the IRAM section.
```c
//#include "net_logging.h"
#include "freertos/ringbuf.h" // testing
...
void app_main(void){
...
    //udp_logging_init("255.255.255.255", 6789, true);
    RingbufHandle_t xRingBuffer = xRingbufferCreate(1024, RINGBUF_TYPE_NOSPLIT);
    (void)xRingBuffer;
```

When I do `idf size-files` I can see that ringbuf.c.obj was already listed and using 3k of IRAM.  After adding xRingbufferCreate() there was no change to that line
```
Per-file contributions to ELF file:
             Object File DRAM .data & 0.bss .rtc_noinit IRAM0 .text & 0.vectors ram_st_total Flash .text & .rodata & .rodata_noload & .appdesc flash_total
...
ringbuf.c.obj          0       0           0        2931           0         2931           0         0                0          0        2931
```
But when I switch back:
```c
#include "net_logging.h"
//#include "freertos/ringbuf.h" // testing
...
void app_main(void){
...
    udp_logging_init("255.255.255.255", 6789, true);
    //RingbufHandle_t xRingBuffer = xRingbufferCreate(1024, RINGBUF_TYPE_NOSPLIT);
    //(void)xRingBuffer;
```
Now the map includes both files, and the IRAM overflows.
```
Per-file contributions to ELF file:
             Object File DRAM .data & 0.bss .rtc_noinit IRAM0 .text & 0.vectors ram_st_total Flash .text & .rodata & .rodata_noload & .appdesc flash_total
...
           ringbuf.c.obj          0       0           0        2931           0         2931           0         0                0          0        2931
...
     stream_buffer.c.obj          0       0           0         781           0          781           0         0                0          0         781
```

**Comment by nopnop2002** [comment]
Thank you for the report.
Please enable xRingBuffer in the latest version.
![config-xRingBuffer](https://github.com/nopnop2002/esp-idf-net-logging/assets/6020549/405ee3e1-637c-4a69-ac59-f4e7d26de5d6)

**Comment by phatpaul** [comment]
It works!  Thank you so much.
