### ISSUE TITLE
Logging in Windows

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [nopnop2002/esp-idf-net-logging#5]
# Logging in Windows

what you made is VERY cool. 

now, most Customers use Windows, and it would be cool if we find easy Windows tools for logging. 

one is Putty, which many Customers already use a lot. 

[https://www.putty.org/](https://www.putty.org/)

is it visible to make [https://github.com/nopnop2002/esp-idf-net-logging](https://github.com/nopnop2002/esp-idf-net-logging) compatible with Putty ? 

or find another Customer friendly Client ? 

Thanks, 

Franz

**Comment by nopnop2002** [comment]
>is it visible to make https://github.com/nopnop2002/esp-idf-net-logging compatible with Putty ?

I don't use Putty, so I don't know what features you need.

Please tell me in detail.

**Comment by diplfranzhoepfinger** [comment]
i need any user friendly Logging Client. 

https://github.com/nopnop2002/esp-idf-net-logging/blob/main/README.md --> all command line Stuff, which is VERY difficult for non Computer Scientists.

**Comment by nopnop2002** [comment]
putty is a simple client and does not seem to have server functionality.

This project requires server functionality.

>i need any user friendly Logging Client.

We need any user friendly Logging Server.

**Comment by diplfranzhoepfinger** [comment]
> We need any user friendly Logging Server.

i understand. this makes sense. 
it is too much Overhead to have inside the ESP32 a Server for Logging, 
so the Server is on the PC, what makes a lot of Sense. 

so next Question: Would it be possible inside the Browser ? 

the ESP32 could host the Webserver, deliver the Server to the Clients Browser, and the Server runs in the Browser. HTML5 and such. Javascript.

**Comment by nopnop2002** [comment]
I found it.

https://apps.microsoft.com/detail/9nblggh52bt0

![udp-server](https://github.com/user-attachments/assets/ebe19adc-2ef4-40d5-b5ef-2a290f21f31d)

**Comment by diplfranzhoepfinger** [comment]
> I found it.


cool cool cool ...

**Comment by nopnop2002** [comment]
You can disable this if you are unable to display ANSI color codes correctly.   
![ANSI-Color](https://github.com/user-attachments/assets/c36b5f74-e85a-48c0-b498-5cb5301f0d24)

![windows-udp-server-2](https://github.com/user-attachments/assets/38d2c698-5690-402c-9419-a7dfe639e4d7)

**Comment by nopnop2002** [comment]
You can reopen this issue at any time.
